set -g prefix C-Space
set -g mouse on

# select panes vim style
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# start windows and panes at index 1
set -g base-index 1
set -g pane-base-index 1

# status bar position
set-option -g status-position top

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'frappe'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
